version: '2.2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/:/usr/share/elasticsearch/data:rw
      - ./logs/:/usr/share/elasticsearch/logs
    networks:
      - elk

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.2.0
    depends_on:
      - elasticsearch
    ports:
      - "80:5601"
    environment:
      - elasticsearch.url=http://elasticsearch:9200
    networks:
      - elk

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.2.0
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "12201:12201"
      - "5044:5044"
    environment:
      - path.config=/usr/share/logstash/pipeline
    networks:
      - elk

networks:
  elk:
    driver: bridge
